version: "3.9"
services:
  nginx: 
    image: rajneeshmehta93/nginx-todo:github-NO-SSL
    restart: always
    ports:
        - 37831:80
        - 47831:443
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
      - static_files:/app/todoapp/staticfiles
    depends_on: 
        - backend
  backend:
    image: rajneeshmehta93/django-todo:github
    restart: always
    expose:
      - 8000
    depends_on: 
        - db
    env_file: 
      - ./.env
    volumes: 
      - static_files:/app/todoapp/staticfiles
  db:
    image: postgres
    restart: always
    volumes: 
    - pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: secretpassword
      PGDATA: /var/lib/postgresql/data/pgdata

  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
        - certbot_conf:/etc/letsencrypt
        - certbot_www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"      

volumes:
  static_files: {}
  pg_data: {}
  certbot_conf: {}
  certbot_www: {}